applisun_compte:
    resource: "@ApplisunCompteBundle/Resources/config/routing.yml"
    prefix:   /
    
app:
    resource: @AppBundle/Controller/
    type:     annotation
    
login:
    pattern:   /login
    defaults:  { _controller: ApplisunCompteBundle:Default:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

rest : 
  type : rest 
  resource : Applisun\CompteBundle\Controller\ApiController
  prefix : /api
  type:     annotation
  
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
