<?php

namespace Applisun\CompteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PretRepository extends EntityRepository
{
}
