<?php

namespace Applisun\CompteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOperationRepository extends EntityRepository
{
    /**
     * Initialize a query builder to get categories by type.
     *
     * @param int $type
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getByTypeQueryBuilder($type)
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.type', 'ASC')
            ->andWhere('t.is_debit = :type')
            ->setParameter('type', $type)
        ;
    }
}
