<?php

namespace Applisun\CompteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirementRepository extends EntityRepository
{
}
